### ISSUE TITLE
Overview of Section 889

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#51] opened 2023-02-11 14:14 UTC
As a Purchase cardholder, A/OPC, or merchant, I want to access information about Section 889 of the NDAA, so that I can understand and conform with Section 889 requirements.

Acceptance criteria
- User can access content from https://docs.google.com/document/d/1uJ42wFu8zKgfmoQTd8HPt9cN0wX3lGVYaBq1U76MZmQ/edit.

**Comment by JessicaMarine1** [comment] 2023-03-30 15:35
@brentryanjohnson this one is ready for your review

**Comment by brentryanjohnson** [comment] 2023-03-31 16:28
@JessicaMarine1 and @johnbeallgsa I think we may have duplicates. Take a look at #53.

**Comment by JessicaMarine1** [comment] 2023-03-31 16:43
Thanks for flagging @brentryanjohnson. I'll close this as a duplicate

**Comment by JessicaMarine1** [comment] 2023-03-31 16:43
Duplicate of #53

**Closed by JessicaMarine1** 2023-03-31 16:43 UTC
Labels: Section 889 Information, Content w/ Ryan
