### ISSUE TITLE
H1 on Smart Bulletins smaller than other h1s

### ISSUE THREAD

**Issue by brentryanjohnson** [GSA/smartpay-website#266] opened 2023-07-31 21:15 UTC
The Smart Bulletins `h1` is smaller than `h1`s on other pages

- The `h1` on Smart Bulletins is styled at `2em`, while those on other pages are styled at `2.44rem`
- This appears to be caused by the Smart Bulletins astro layout lacking `usa-prose` classes on the main element that the other pages have
- `usa-prose` classes cause layout issues with full-width tables

> **Note**
> The Policies page has the same, full-width table layout, but that page has the `usa-prose` classes on the `main` element

## Policies page
![Screenshot showing Policies title and a table](https://github.com/GSA/smartpay-website/assets/32855580/5aea8c91-891f-48a5-8994-8afb56267fb7)

## Smart Bulletins page
![Screenshot showing Smart Bulletins page title and a table](https://github.com/GSA/smartpay-website/assets/32855580/5dfc5a7b-ac86-4fce-99a9-31f24aa313d2)

**Comment by weiwang-gsa** [comment] 2023-08-01 15:46
@brentryanjohnson, As I digging into the issue, I found the root cause is usa-prose paragraph has max-width settings that  make it not fit with full size template, below changes are made:

- pull common section out and made component for full size template to make sure consistency for all full size page. So in future if there is no page using full size template, it will have exact same settings all across. 
-  fix the usa-prose issue with full size template. Change max-width to fit content for full size page only, and keep all the other settings of usa-prose class, this it so avoid modification on individual p, h1, h2 h3...etc to match with usa-prose

 this is ready for design review: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/preview/gsa/smartpay-website/staging/policies-and-audits/smart-bulletins/

**Comment by brentryanjohnson** [comment] 2023-08-05 00:08
Looks good!

**Comment by weiwang-gsa** [comment] 2023-08-07 13:14
@rebekahperillo passed Ryan's review, now it is ready for QA: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/preview/gsa/smartpay-website/staging/policies-and-audits/smart-bulletins/

**Comment by rebekahperillo** [comment] 2023-08-08 10:46
Looks good! Moving to DONE. Thank you!

**Closed** 2023-08-21 17:42 UTC
Labels: Sprint 14
