### ISSUE TITLE
Content Updates

### ISSUE THREAD

**Issue by rebekahperillo** [GSA/smartpay-website#218] opened 2023-07-19 17:34 UTC
Prior to launch, we'll have to make some content updates on the program website.

Here's a running list:
https://docs.google.com/document/d/1FvR3hje3er5TAWan5nHoD9jZBP2tc6bjT8Ye2cWfQWI/edit

**Comment by JessicaMarine1** [comment] 2023-07-26 16:44
Closing this issue; duplicate of #19

**Closed by JessicaMarine1** 2023-07-26 16:44 UTC
