### ISSUE TITLE
Auto-generate heading id attributes

### ISSUE THREAD

**Issue by brentryanjohnson** [GSA/smartpay-website#87] opened 2023-02-16 20:46 UTC
> As a user, I want a linked summary of the headings on long pages of content so I can jump to sections that cover what I'm looking for without having to scroll the entire page.

Acceptance criteria:
- There's an optional way to include in-page navigation to sections of the page

**Comment by brentryanjohnson** [comment] 2023-02-16 20:52
The config currently includes a package that _should_ autogenerate in-page anchors on heading elements (`markdown-it-anchor`), but it's not currently generating the aforementioned `id`s on heading elements.

**Comment by JessicaMarine1** [comment] 2023-06-14 19:24
Duplicate of #115

**Closed by JessicaMarine1** 2023-06-14 19:24 UTC
