### ISSUE TITLE
DoD 889 Bot

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#53] opened 2023-02-11 14:16 UTC
Path: resources/tools/section-889
File name: 
Design: [Resources > 889 Tool](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1374%3A36813&t=NB2CPqpZgPZBO4xz-1)
Template: [Sidebar Template](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1452-41800&t=ZdXxtCQnJUFtcq4C-4)
_______________ 

- Content: https://docs.google.com/document/d/1eo8SEAIVbperE57xJhm_14y623TGWaz9StZMta1J5SM/edit.

**Comment by brentryanjohnson** [comment] 2023-03-28 15:54
@johnbeallgsa I took a first pass at it. ✅

**Comment by johnbeallgsa** [comment] 2023-03-28 17:56
@brentryanjohnson Moving to Content Ready for Grooming

**Comment by JessicaMarine1** [comment] 2023-06-22 15:58
@klohman I don't think you finished annotating this one. Also, the copy in Figma needs to be updated to match the track changes in the google doc.

**Comment by klohman** [comment] 2023-06-22 20:24
> @klohman I don't think you finished annotating this one. Also, the copy in Figma needs to be updated to match the track changes in the google doc.

Updated Figma. 

@rebekahperillo Is it correct that users email to **info@section889request.com** then receive an email from **info@section889req.com**? Or should both of these be **info@section889request.com**?

**Comment by JessicaMarine1** [comment] 2023-06-22 20:38
@klohman In Rebekah's absence, I can confirm that users send an email to: info@section889request.com but get a response from info@section889req.com

**Comment by weiwang-gsa** [comment] 2023-07-20 14:12
@klohman figma design have "889 Tool" as page title, but in google doc page title is "Section 889 Tools", which one I should follow? Thanks


![Image](https://github.com/GSA/smartpay-website/assets/119954777/e8ee8c8e-544f-42c9-ae0e-1d73e5c4808d)

**Comment by rebekahperillo** [comment] 2023-07-20 15:22
@klohman @weiwang-gsa There are two tools on the page - our tool and the DoD bot, so I would think we should say "Section 889 Tools". Thoughts?

**Comment by klohman** [comment] 2023-07-20 15:44
@weiwang-gsa @rebekahperillo I think it should be "Section 889 Tools" and follow the content doc.

**Comment by weiwang-gsa** [comment] 2023-07-20 18:05
@klohman It is ready for design review: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/resources/tools/section-889/

**Comment by klohman** [comment] 2023-07-20 18:53
@rebekahperillo Ready for your review. 

Note: the link for [Section 889 Bot Operation Update as of 1/20/23](https://dodprocurementtoolbox.com/articles/section-889-bot-operation-update-as-of-12023) is working, but that page seems to be blank (for me, anyway). This is external so nothing we can do about it, but we may not want to link there if it's broken. 

<img width="1235" alt="Screen Shot 2023-07-20 at 2 50 54 PM" src="https://github.com/GSA/smartpay-website/assets/18366192/f5d1dd0e-a2f4-468c-9511-0bb0368889f8">

**Comment by rebekahperillo** [comment] 2023-07-22 12:30
@klohman Made a note about the link, thank you!

Moving to "Done"! Thank you!

**Closed** 2023-08-21 17:42 UTC
Labels: Sprint 13, 7.1 Tools
